export const SET_THEME = "SET_THEME";
export const WALLET_INSTALLED = "WALLET_INSTALLED";
export const CONNECT_WALLET = "CONNECT_WALLET";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_CHAIN = "GET_CHAIN";
export const SET_CONTRACT_PROVIDER = "SET_CONTRACT_PROVIDER";
export const SET_CONTRACT_SIGNER = "SET_CONTRACT_SIGNER";